spring.application.name=spring-board

spring.devtools.livereload.enabled=true

logging.level.net.likelion.bebc25=debug

## JDBC
spring.datasource.url=jdbc:mysql://localhost:3306/board_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root


# 내장형/외장형 데이터베이스 여부와 상관없이 기동 시 무조건 초기화 (schema/data.sql)
spring.sql.init.mode=always

# 초기화 스크립트 실행을 완전히 차단 (데이터 누적 및 보존을 위해 물리 DB 연동 시 필수 지정)
# spring.sql.init.mode=never

# 기본값으로 H2 등의 내장형 메모리 데이터베이스가 작동할 때만 초기화 스크립트 작동, 단위테스트나 통합테스트 시
# spring.sql.init.mode=embedded

# 커넥션 풀 Hikari
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000